//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Documento = new HashSet<Documento>();
            this.Registro = new HashSet<Registro>();
        }
    
        public int IdItem { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdTipoItem { get; set; }
        public string Placa { get; set; }
        public string Informacion { get; set; }
    
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Registro> Registro { get; set; }
    }
}
