//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Item = new HashSet<Item>();
            this.Registro = new HashSet<Registro>();
        }
    
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public decimal Telefono { get; set; }
        public string Empresa { get; set; }
        public string Correo { get; set; }
    
        public virtual ICollection<Item> Item { get; set; }
        public virtual ICollection<Registro> Registro { get; set; }
    }
}
